

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=furniture
    ports:
      - "3307:3307"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/furniture?autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - db
    entrypoint: ["sh", "-c", "/wait-for-it.sh db:3306 -- java -jar /app.jar"]
